# Generated by Django 2.1.5 on 2019-01-25 10:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UserAccount', '0004_auto_20190125_0104'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='location',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='user_type',
        ),
    ]
