# Generated by Django 2.1.5 on 2019-01-25 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='about',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(max_length=100, null=True)),
                ('descrption1', models.CharField(max_length=300, null=True)),
                ('description2', models.CharField(max_length=300, null=True)),
                ('photo', models.ImageField(default='assets/img/about/about.jpg', upload_to='static/assets/aboutImages')),
            ],
        ),
        migrations.CreateModel(
            name='aboutCreativeTeam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, null=True)),
                ('designation', models.CharField(max_length=150, null=True)),
                ('description', models.CharField(max_length=400, null=True)),
                ('photo', models.ImageField(default='assets/img/team/team_member_1.jpg', upload_to='static/assets/creativeTeamImages')),
            ],
        ),
        migrations.CreateModel(
            name='aboutTestimonials',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, null=True)),
                ('description', models.CharField(max_length=400, null=True)),
                ('photo', models.ImageField(default='assets/img/testimonial/team-member-1.jpg', upload_to='static/assets/testimonialsImages')),
            ],
        ),
    ]
