# Generated by Django 2.1.5 on 2019-01-25 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about_us', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='status',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='aboutcreativeteam',
            name='status',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='abouttestimonials',
            name='status',
            field=models.BooleanField(null=True),
        ),
    ]
