# Generated by Django 2.1.5 on 2019-01-25 14:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about_us', '0002_auto_20190125_1920'),
    ]

    operations = [
        migrations.RenameField(
            model_name='about',
            old_name='descrption1',
            new_name='description1',
        ),
    ]
