# Generated by Django 2.1.5 on 2019-01-26 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blogCategory', models.CharField(max_length=50, null=True)),
                ('blogName', models.CharField(max_length=50, null=True)),
                ('postedBy', models.CharField(max_length=50, null=True)),
                ('blogDate', models.DateField(null=True)),
                ('blogAbout', models.CharField(max_length=150, null=True)),
                ('blogDescription', models.CharField(max_length=500, null=True)),
                ('blogQuote', models.CharField(max_length=300, null=True)),
                ('blogTag', models.CharField(max_length=100, null=True)),
                ('photo', models.ImageField(default='static/assets/blogImages/blog1.jpg', upload_to='static/assets/blogImages')),
            ],
        ),
    ]
