# Generated by Django 2.1.5 on 2019-01-26 12:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='blogComments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('senderName', models.CharField(max_length=50)),
                ('date', models.DateTimeField()),
                ('comment', models.CharField(max_length=200)),
                ('photo', models.ImageField(default='static/assets/blogCommentsImages/comment-icon.png', upload_to='static/assets/blogCommentsImages')),
                ('blog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blogs.Blog')),
            ],
        ),
    ]
