# Generated by Django 2.1.5 on 2019-01-26 13:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0003_auto_20190126_1809'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogcomments',
            name='blog',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blogs.Blog'),
        ),
        migrations.AlterField(
            model_name='blogcomments',
            name='date',
            field=models.DateTimeField(null=True),
        ),
    ]
