# Generated by Django 2.1.5 on 2019-01-25 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=300, null=True)),
                ('address', models.CharField(max_length=250, null=True)),
                ('email', models.EmailField(max_length=250, null=True)),
                ('phone_no', models.CharField(max_length=100, null=True)),
                ('workingDay_start', models.CharField(max_length=100, null=True)),
                ('workingDay_end', models.CharField(max_length=100, null=True)),
                ('workingTime_start', models.IntegerField(max_length=100, null=True)),
                ('workingTime_startZone', models.CharField(max_length=50, null=True)),
                ('workingTime_end', models.IntegerField(max_length=100, null=True)),
                ('workingTime_endZone', models.CharField(max_length=50, null=True)),
            ],
        ),
    ]
