# Generated by Django 2.1.5 on 2019-01-25 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact_us', '0003_auto_20190125_1716'),
    ]

    operations = [
        migrations.CreateModel(
            name='contactMessages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('senderName', models.CharField(max_length=100, null=True)),
                ('sender_phoneNo', models.CharField(max_length=100, null=True)),
                ('sender_email', models.EmailField(max_length=100, null=True)),
                ('msg_subject', models.CharField(max_length=150, null=True)),
                ('msg', models.CharField(max_length=300, null=True)),
            ],
        ),
    ]
