# Generated by Django 2.1.5 on 2019-01-25 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='slider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=150, null=True)),
                ('details', models.CharField(max_length=250, null=True)),
                ('model_pic', models.ImageField(default='static/assets/img/slider1.jpg', upload_to='static/assets/sliderImages')),
            ],
        ),
    ]
